-- =====================================================
-- SISTEMA DE NÓMINA Y RRHH — SCHEMA COMPLETO
-- Ejecutar este script en el SQL Editor de Supabase
-- =====================================================

CREATE TABLE IF NOT EXISTS usuarios (id BIGSERIAL PRIMARY KEY, nombre TEXT NOT NULL, usuario TEXT UNIQUE NOT NULL, clave TEXT NOT NULL, rol TEXT DEFAULT 'consulta', activo BOOLEAN DEFAULT TRUE, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS departamentos (id BIGSERIAL PRIMARY KEY, nombre TEXT NOT NULL, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS cargos (id BIGSERIAL PRIMARY KEY, nombre TEXT NOT NULL, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS empleados (id BIGSERIAL PRIMARY KEY, fecha_ingreso DATE, cedula TEXT, nombre TEXT NOT NULL, telefono TEXT, departamento_id BIGINT, cargo_id BIGINT, sueldo NUMERIC(15,2) DEFAULT 0, bono_alimentacion NUMERIC(15,2) DEFAULT 0, otros_ingresos NUMERIC(15,2) DEFAULT 0, saldo_prestamo NUMERIC(15,2) DEFAULT 0, anticipos_prestaciones NUMERIC(15,2) DEFAULT 0, activo BOOLEAN DEFAULT TRUE, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS nominas (id BIGSERIAL PRIMARY KEY, fecha_pago DATE NOT NULL, empleado_id BIGINT, empleado TEXT, cargo TEXT, tasa_bcv NUMERIC(15,2), salario_minimo_bs NUMERIC(15,2), salario_base NUMERIC(15,2), bono_alimentacion NUMERIC(15,2), otros_ingresos NUMERIC(15,2), dias_faltantes NUMERIC(10,2) DEFAULT 0, otras_asignaciones NUMERIC(15,2) DEFAULT 0, horas_descuento NUMERIC(10,2) DEFAULT 0, otros_descuentos NUMERIC(15,2) DEFAULT 0, adelantos NUMERIC(15,2) DEFAULT 0, prestamos NUMERIC(15,2) DEFAULT 0, ivss_usd NUMERIC(15,4) DEFAULT 0, rpe_usd NUMERIC(15,4) DEFAULT 0, faov_usd NUMERIC(15,4) DEFAULT 0, descuentos_ley_usd NUMERIC(15,4) DEFAULT 0, neto_usd NUMERIC(15,2) DEFAULT 0, neto_bs NUMERIC(15,2) DEFAULT 0, estado TEXT DEFAULT 'Procesado', created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS historico_salarios (id BIGSERIAL PRIMARY KEY, empleado_id BIGINT NOT NULL, mes TEXT NOT NULL, sueldo_base NUMERIC(15,2) DEFAULT 0, bono_alimentacion NUMERIC(15,2) DEFAULT 0, subsidio NUMERIC(15,2) DEFAULT 0, created_at TIMESTAMPTZ DEFAULT NOW(), UNIQUE(empleado_id, mes));
CREATE TABLE IF NOT EXISTS prenomina_borrador (id BIGINT PRIMARY KEY, fecha_pago DATE, tasa_bcv NUMERIC(15,2), salario_minimo NUMERIC(15,2), lunes INT, filas JSONB, updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS vacaciones (id BIGSERIAL PRIMARY KEY, empleado_id BIGINT, empleado TEXT, periodo TEXT, fecha_inicio DATE, gran_total_usd NUMERIC(15,2), gran_total_bs NUMERIC(15,2), total_usd NUMERIC(15,2), total_bs NUMERIC(15,2), detalle_calculo JSONB, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS utilidades (id BIGSERIAL PRIMARY KEY, periodo TEXT, fecha_pago DATE, empleado_id BIGINT, empleado TEXT, cargo TEXT, tasa_bcv NUMERIC(15,2), salario_base NUMERIC(15,2), dias_trabajados NUMERIC(10,2), dias_pagados NUMERIC(10,2), total_usd NUMERIC(15,2), total_bs NUMERIC(15,2), subsidio_usd NUMERIC(15,2), subsidio_bs NUMERIC(15,2), gran_total_usd NUMERIC(15,2), gran_total_bs NUMERIC(15,2), porcentaje_pagado NUMERIC(5,2) DEFAULT 100, porcentaje_acumulado NUMERIC(5,2) DEFAULT 100, total_usd_anual NUMERIC(15,2), total_bs_anual NUMERIC(15,2), gran_total_usd_anual NUMERIC(15,2), gran_total_bs_anual NUMERIC(15,2), detalle_calculo JSONB, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS antiguedad (id BIGSERIAL PRIMARY KEY, empleado_id BIGINT, empleado TEXT, cargo TEXT, fecha_ingreso DATE, fecha_corte DATE, tiempo_servicio TEXT, total_metodo1_bs NUMERIC(15,2), total_metodo2_bs NUMERIC(15,2), monto_definitivo_bs NUMERIC(15,2), monto_definitivo_usd NUMERIC(15,2), tasa_bcv NUMERIC(15,2), detalle_calculo JSONB, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS prestaciones (id BIGSERIAL PRIMARY KEY, empleado_id BIGINT, empleado TEXT, cargo TEXT, fecha_ingreso DATE, fecha_calculo DATE, motivo TEXT, tiempo_servicio TEXT, dias_pagar NUMERIC(10,2), salario_base NUMERIC(15,2), tasa_bcv NUMERIC(15,2), total_usd NUMERIC(15,2), total_bs NUMERIC(15,2), detalle_calculo JSONB, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS anticipos_prestaciones (id BIGSERIAL PRIMARY KEY, empleado_id BIGINT NOT NULL, monto_bs NUMERIC(15,2) NOT NULL, fecha DATE NOT NULL, concepto TEXT, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS tasas_mensuales (mes TEXT PRIMARY KEY, tasa_promedio NUMERIC(10,4), tasa_anual NUMERIC(10,4), tasa_mensual NUMERIC(10,4), tasa_dolar NUMERIC(15,2), created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS parametros_config (id BIGINT PRIMARY KEY, nombre_empresa TEXT, rif_empresa TEXT, dias_utilidades INT DEFAULT 30, updated_at TIMESTAMPTZ DEFAULT NOW());

DO $$ DECLARE t TEXT; BEGIN FOR t IN SELECT tablename FROM pg_tables WHERE schemaname = 'public' LOOP EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t); EXECUTE format('DROP POLICY IF EXISTS "Allow all" ON public.%I', t); EXECUTE format('CREATE POLICY "Allow all" ON public.%I FOR ALL USING (true) WITH CHECK (true)', t); END LOOP; END $$;

INSERT INTO usuarios (nombre, usuario, clave, rol, activo) VALUES ('Super Administrador', 'master', 'master123', 'master', true) ON CONFLICT (usuario) DO NOTHING;
INSERT INTO parametros_config (id, nombre_empresa, rif_empresa, dias_utilidades) VALUES (1, 'MI EMPRESA, C.A.', 'J-00000000-0', 30) ON CONFLICT (id) DO NOTHING;